name: float
version: 0.7.3
date: 11/05/2016
description: Integration of mpfr, mpfi, mpc, fplll and cxsc in GAP

authors:
    - name: Laurent Bartholdi
      url: http://www.uni-math.gwdg.de/laurent

maintainers:
    - name: Laurent Bartholdi
      url: http://www.uni-math.gwdg.de/laurent

GAP: ">=4.5.0"

needed-pkgs:
    - name: "GAPDoc"
      version: ">=1.0"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: http://gap-packages.github.io/float/
readme: https://gap-packages.github.io/float/README
packageinfo: https://gap-packages.github.io/float/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/float/releases/download/v0.7.3/float-0.7.3.tar.gz

abstract: The <span class="pkgname">float</span> package allows                     GAP to manipulate floating-point numbers with arbitrary                     precision. It is based on MPFR, MPFI, MPC, CXSC, FPLLL

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
