name: float
version: 0.9.9
date: 2021-10-17
description: |
    Integration of mpfr, mpfi, mpc, fplll and cxsc in GAP

authors:
    - name: Laurent Bartholdi
      url: http://www.uni-math.gwdg.de/laurent

maintainers:
    - name: Laurent Bartholdi
      url: http://www.uni-math.gwdg.de/laurent

GAP: ">=4.9.0"

needed-pkgs:
    - name: "GAPDoc"
      version: ">=1.0"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://gap-packages.github.io/float/
readme: README.md
packageinfo: https://gap-packages.github.io/float/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/float/releases/download/v0.9.9/float-0.9.9.tar.gz

abstract: |
    The <span class="pkgname">float</span> package allows                     GAP to manipulate floating-point numbers with arbitrary                     precision. It is based on MPFR, MPFI, MPC, CXSC, FPLLL

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
